import { PrismaClient } from '@prisma/client';

export default async function iakPrabayarSeed(prisma: PrismaClient) {
  const types = [
    { id: 1, type: 'pulsa' },
    { id: 2, type: 'data' },
    { id: 3, type: 'etoll' },
    { id: 4, type: 'voucher' },
    { id: 5, type: 'game' },
    { id: 6, type: 'pln' },
    { id: 7, type: 'esiminternational' },
    { id: 8, type: 'Bangladesh' },
    { id: 9, type: 'China' },
    { id: 10, type: 'Malaysia' },
    { id: 11, type: 'Philipines' },
    { id: 12, type: 'Singapore' },
    { id: 13, type: 'Taiwan' },
    { id: 14, type: 'Thailand' },
    { id: 15, type: 'Vietnam' }
  ];

  for (const t of types) {
    await prisma.iakPrabayarType.upsert({
      where: { id: t.id },
      update: { type: t.type },
      create: { id: t.id, type: t.type }
    });
  }

  const operators = [
    { id: 1, name: 'axis', typeId: 1 },
    { id: 2, name: 'indosat', typeId: 1 },
    { id: 3, name: 'smart', typeId: 1 },
    { id: 4, name: 'telkomsel', typeId: 1 },
    { id: 5, name: 'three', typeId: 1 },
    { id: 6, name: 'xixi_games', typeId: 1 },
    { id: 7, name: 'xl', typeId: 1 },
    { id: 8, name: 'by.U', typeId: 1 },
    { id: 9, name: 'axis_paket_internet', typeId: 2 },
    { id: 10, name: 'telkomsel', typeId: 2 },
    { id: 11, name: 'indosat_paket_internet', typeId: 2 },
    { id: 12, name: 'smartfren_paket_internet', typeId: 2 },
    { id: 13, name: 'tri_paket_internet', typeId: 2 },
    { id: 14, name: 'telkomsel_paket_internet', typeId: 2 },
    { id: 15, name: 'xl_paket_internet', typeId: 2 },
    { id: 16, name: 'dana', typeId: 3 },
    { id: 17, name: 'mandiri_e-toll', typeId: 3 },
    { id: 18, name: 'indomaret_card_e-money', typeId: 3 },
    { id: 19, name: 'gopay_e-money', typeId: 3 },
    { id: 20, name: 'linkaja', typeId: 3 },
    { id: 21, name: 'ovo', typeId: 3 },
    { id: 22, name: 'shopee_pay', typeId: 3 },
    { id: 23, name: 'tix_id', typeId: 3 },
    { id: 24, name: 'alfamart', typeId: 4 },
    { id: 25, name: 'carrefour', typeId: 4 },
    { id: 26, name: 'indomaret', typeId: 4 },
    { id: 27, name: 'map', typeId: 4 },
    { id: 28, name: 'tokopedia', typeId: 4 },
    { id: 29, name: 'traveloka', typeId: 4 },
    { id: 30, name: 'udemy', typeId: 4 },
    { id: 31, name: 'arena_of_valor', typeId: 5 },
    { id: 32, name: 'battlenet_sea', typeId: 5 },
    { id: 33, name: 'bleach_mobile_3d', typeId: 5 },
    { id: 34, name: 'call_of_duty_mobile', typeId: 5 },
    { id: 35, name: 'dragon_nest_m_-_sea', typeId: 5 },
    { id: 36, name: 'era_of_celestials', typeId: 5 },
    { id: 37, name: 'free_fire', typeId: 5 },
    { id: 38, name: 'garena', typeId: 5 },
    { id: 39, name: 'gemscool', typeId: 5 },
    { id: 40, name: 'genshin_impact', typeId: 5 },
    { id: 41, name: 'google_play_us_region', typeId: 5 },
    { id: 42, name: 'google_play_indonesia', typeId: 5 },
    { id: 43, name: 'itunes_us_region', typeId: 5 },
    { id: 44, name: 'lyto', typeId: 5 },
    { id: 45, name: 'joox', typeId: 5 },
    { id: 46, name: 'megaxus', typeId: 5 },
    { id: 47, name: 'mobile_legend', typeId: 5 },
    { id: 48, name: 'razer_pin', typeId: 5 },
    { id: 49, name: 'playstation', typeId: 5 },
    { id: 50, name: 'steam_sea', typeId: 5 },
    { id: 51, name: 'wave_game', typeId: 5 },
    { id: 52, name: 'league_of_legends_wild_rift', typeId: 5 },
    { id: 53, name: 'lifeafter', typeId: 5 },
    { id: 54, name: 'light_of_thel:_glory_of_cepheus', typeId: 5 },
    { id: 55, name: 'lords_mobile', typeId: 5 },
    { id: 56, name: 'marvel_super_war', typeId: 5 },
    { id: 57, name: 'minecraft', typeId: 5 },
    { id: 58, name: 'netflix', typeId: 5 },
    { id: 59, name: 'nintendo_eshop', typeId: 5 },
    { id: 60, name: 'point_blank', typeId: 5 },
    { id: 61, name: 'pubg_mobile', typeId: 5 },
    { id: 62, name: 'pubg_pc', typeId: 5 },
    { id: 63, name: 'ragnarok_m', typeId: 5 },
    { id: 64, name: 'skyegrid', typeId: 5 },
    { id: 65, name: 'speed_drifters', typeId: 5 },
    { id: 66, name: 'vidio', typeId: 5 },
    { id: 67, name: 'viu', typeId: 5 },
    { id: 68, name: 'wifi_id', typeId: 5 },
    { id: 69, name: 'pln', typeId: 6 },
    { id: 70, name: 'esim_afghanistan', typeId: 7 },
    { id: 71, name: 'esim_albania', typeId: 7 },
    { id: 72, name: 'esim_algeria', typeId: 7 },
    { id: 73, name: 'esim_andorra', typeId: 7 },
    { id: 74, name: 'esim_anguilla', typeId: 7 },
    { id: 75, name: 'esim_antigua_and_barbuda', typeId: 7 },
    { id: 76, name: 'esim_argentina', typeId: 7 },
    { id: 77, name: 'esim_armenia', typeId: 7 },
    { id: 78, name: 'esim_australia', typeId: 7 },
    { id: 79, name: 'esim_austria', typeId: 7 },
    { id: 80, name: 'esim_azerbaijan', typeId: 7 },
    { id: 81, name: 'esim_bahrain', typeId: 7 },
    { id: 82, name: 'esim_bangladesh', typeId: 7 },
    { id: 83, name: 'esim_barbados', typeId: 7 },
    { id: 84, name: 'esim_belarus', typeId: 7 },
    { id: 85, name: 'esim_belgium', typeId: 7 },
    { id: 86, name: 'esim_benin', typeId: 7 },
    { id: 87, name: 'esim_bermuda', typeId: 7 },
    { id: 88, name: 'esim_bolivia', typeId: 7 },
    { id: 89, name: 'esim_bosnia_and_herzegovina', typeId: 7 },
    { id: 90, name: 'esim_brazil', typeId: 7 },
    { id: 91, name: 'esim_british_virgin_islands', typeId: 7 },
    { id: 92, name: 'esim_bulgaria', typeId: 7 },
    { id: 93, name: 'esim_cambodia', typeId: 7 },
    { id: 94, name: 'esim_canada', typeId: 7 },
    { id: 95, name: 'esim_cape_verde', typeId: 7 },
    { id: 96, name: 'esim_cayman_islands', typeId: 7 },
    { id: 97, name: 'esim_chad', typeId: 7 },
    { id: 98, name: 'esim_chile', typeId: 7 },
    { id: 99, name: 'esim_china', typeId: 7 },
    { id: 100, name: 'esim_colombia', typeId: 7 },
    { id: 101, name: 'esim_costa_rica', typeId: 7 },
    { id: 102, name: 'esim_croatia', typeId: 7 },
    { id: 103, name: 'esim_curacao', typeId: 7 },
    { id: 104, name: 'esim_cyprus', typeId: 7 },
    { id: 105, name: 'esim_czechia', typeId: 7 },
    { id: 106, name: 'esim_dr_congo', typeId: 7 },
    { id: 107, name: 'esim_denmark', typeId: 7 },
    { id: 108, name: 'esim_dominica', typeId: 7 },
    { id: 109, name: 'esim_dominican_republic', typeId: 7 },
    { id: 110, name: 'esim_ecuador', typeId: 7 },
    { id: 111, name: 'esim_egypt', typeId: 7 },
    { id: 112, name: 'esim_el_salvador', typeId: 7 },
    { id: 113, name: 'esim_estonia', typeId: 7 },
    { id: 114, name: 'esim_ethiopia', typeId: 7 },
    { id: 115, name: 'esim_faroe_islands', typeId: 7 },
    { id: 116, name: 'esim_fiji', typeId: 7 },
    { id: 117, name: 'esim_finland', typeId: 7 },
    { id: 118, name: 'esim_france', typeId: 7 },
    { id: 119, name: 'esim_gabon', typeId: 7 },
    { id: 120, name: 'esim_georgia', typeId: 7 },
    { id: 121, name: 'esim_germany', typeId: 7 },
    { id: 122, name: 'esim_ghana', typeId: 7 },
    { id: 123, name: 'esim_gibraltar', typeId: 7 },
    { id: 124, name: 'esim_greece', typeId: 7 },
    { id: 125, name: 'esim_grenada', typeId: 7 },
    { id: 126, name: 'esim_guadeloupe', typeId: 7 },
    { id: 127, name: 'esim_guatemala', typeId: 7 },
    { id: 128, name: 'esim_guyana', typeId: 7 },
    { id: 129, name: 'esim_honduras', typeId: 7 },
    { id: 130, name: 'esim_hong_kong', typeId: 7 },
    { id: 131, name: 'esim_hungary', typeId: 7 },
    { id: 132, name: 'esim_iceland', typeId: 7 },
    { id: 133, name: 'esim_india', typeId: 7 },
    { id: 134, name: 'esim_indonesia', typeId: 7 },
    { id: 135, name: 'esim_iran', typeId: 7 },
    { id: 136, name: 'esim_iraq', typeId: 7 },
    { id: 137, name: 'esim_ireland', typeId: 7 },
    { id: 138, name: 'esim_israel', typeId: 7 },
    { id: 139, name: 'esim_italy', typeId: 7 },
    { id: 140, name: 'esim_jamaica', typeId: 7 },
    { id: 141, name: 'esim_japan', typeId: 7 },
    { id: 142, name: 'esim_jordan', typeId: 7 },
    { id: 143, name: 'esim_kazakhstan', typeId: 7 },
    { id: 144, name: 'esim_kenya', typeId: 7 },
    { id: 145, name: 'esim_kosovo', typeId: 7 },
    { id: 146, name: 'esim_kuwait', typeId: 7 },
    { id: 147, name: 'esim_kyrgyzstan', typeId: 7 },
    { id: 148, name: 'esim_laos', typeId: 7 },
    { id: 149, name: 'esim_latvia', typeId: 7 },
    { id: 150, name: 'esim_liechtenstein', typeId: 7 },
    { id: 151, name: 'esim_lithuania', typeId: 7 },
    { id: 152, name: 'esim_luxembourg', typeId: 7 },
    { id: 153, name: 'esim_macau', typeId: 7 },
    { id: 154, name: 'esim_madagascar', typeId: 7 },
    { id: 155, name: 'esim_malawi', typeId: 7 },
    { id: 156, name: 'esim_malaysia', typeId: 7 },
    { id: 157, name: 'esim_malta', typeId: 7 },
    { id: 158, name: 'esim_mauritius', typeId: 7 },
    { id: 159, name: 'esim_mexico', typeId: 7 },
    { id: 160, name: 'esim_moldova', typeId: 7 },
    { id: 161, name: 'esim_mongolia', typeId: 7 },
    { id: 162, name: 'esim_montenegro', typeId: 7 },
    { id: 163, name: 'esim_montserrat', typeId: 7 },
    { id: 164, name: 'esim_morocco', typeId: 7 },
    { id: 165, name: 'esim_mozambique', typeId: 7 },
    { id: 166, name: 'esim_nepal', typeId: 7 },
    { id: 167, name: 'esim_netherlands', typeId: 7 },
    { id: 168, name: 'esim_new_zealand', typeId: 7 },
    { id: 169, name: 'esim_nicaragua', typeId: 7 },
    { id: 170, name: 'esim_niger', typeId: 7 },
    { id: 171, name: 'esim_nigeria', typeId: 7 },
    { id: 172, name: 'esim_north_macedonia', typeId: 7 },
    { id: 173, name: 'esim_norway', typeId: 7 },
    { id: 174, name: 'esim_oman', typeId: 7 },
    { id: 175, name: 'esim_pakistan', typeId: 7 },
    { id: 176, name: 'esim_palestine', typeId: 7 },
    { id: 177, name: 'esim_panama', typeId: 7 },
    { id: 178, name: 'esim_papua_new_guinea', typeId: 7 },
    { id: 179, name: 'esim_paraguay', typeId: 7 },
    { id: 180, name: 'esim_peru', typeId: 7 },
    { id: 181, name: 'esim_philippines', typeId: 7 },
    { id: 182, name: 'esim_poland', typeId: 7 },
    { id: 183, name: 'esim_portugal', typeId: 7 },
    { id: 184, name: 'esim_puerto_rico', typeId: 7 },
    { id: 185, name: 'esim_qatar', typeId: 7 },
    { id: 186, name: 'esim_republic_of_the_congo', typeId: 7 },
    { id: 187, name: 'esim_reunion', typeId: 7 },
    { id: 188, name: 'esim_romania', typeId: 7 },
    { id: 189, name: 'esim_rwanda', typeId: 7 },
    { id: 190, name: 'esim_saint_kitts_and_nevis', typeId: 7 },
    { id: 191, name: 'esim_saint_lucia', typeId: 7 },
    { id: 192, name: 'esim_saint_vincent_and_the_grenadines', typeId: 7 },
    { id: 193, name: 'esim_samoa', typeId: 7 },
    { id: 194, name: 'esim_saudi_arabia', typeId: 7 },
    { id: 195, name: 'esim_senegal', typeId: 7 },
    { id: 196, name: 'esim_serbia', typeId: 7 },
    { id: 197, name: 'esim_singapore', typeId: 7 },
    { id: 198, name: 'esim_slovakia', typeId: 7 },
    { id: 199, name: 'esim_slovenia', typeId: 7 },
    { id: 200, name: 'esim_south_africa', typeId: 7 },
    { id: 201, name: 'esim_south_korea', typeId: 7 },
    { id: 202, name: 'esim_spain', typeId: 7 },
    { id: 203, name: 'esim_sri_lanka', typeId: 7 },
    { id: 204, name: 'esim_sudan', typeId: 7 },
    { id: 205, name: 'esim_suriname', typeId: 7 },
    { id: 206, name: 'esim_sweden', typeId: 7 },
    { id: 207, name: 'esim_switzerland', typeId: 7 },
    { id: 208, name: 'esim_taiwan', typeId: 7 },
    { id: 209, name: 'esim_tajikistan', typeId: 7 },
    { id: 210, name: 'esim_tanzania', typeId: 7 },
    { id: 211, name: 'esim_thailand', typeId: 7 },
    { id: 212, name: 'esim_tonga', typeId: 7 },
    { id: 213, name: 'esim_trinidad_and_tobago', typeId: 7 },
    { id: 214, name: 'esim_tunisia', typeId: 7 },
    { id: 215, name: 'esim_turkey', typeId: 7 },
    { id: 216, name: 'esim_turks_and_caicos_islands', typeId: 7 },
    { id: 217, name: 'esim_uganda', typeId: 7 },
    { id: 218, name: 'esim_ukraine', typeId: 7 },
    { id: 219, name: 'esim_united_arab_emirates', typeId: 7 },
    { id: 220, name: 'esim_united_kingdom', typeId: 7 },
    { id: 221, name: 'esim_united_states', typeId: 7 },
    { id: 222, name: 'esim_uruguay', typeId: 7 },
    { id: 223, name: 'esim_uzbekistan', typeId: 7 },
    { id: 224, name: 'esim_vanuatu', typeId: 7 },
    { id: 225, name: 'esim_venezuela', typeId: 7 },
    { id: 226, name: 'esim_vietnam', typeId: 7 },
    { id: 227, name: 'esim_zambia', typeId: 7 },
    { id: 228, name: 'bangladesh_topup', typeId: 8 },
    { id: 229, name: 'china_topup', typeId: 9 },
    { id: 230, name: 'malaysia_topup', typeId: 10 },
    { id: 231, name: 'celcom', typeId: 10 },
    { id: 232, name: 'digi', typeId: 10 },
    { id: 233, name: 'maxis', typeId: 10 },
    { id: 234, name: 'tunetalk', typeId: 10 },
    { id: 235, name: 'umobile', typeId: 10 },
    { id: 236, name: 'xox', typeId: 10 },
    { id: 237, name: 'globe', typeId: 11 },
    { id: 238, name: 'smart', typeId: 11 },
    { id: 239, name: 'sun_telecom', typeId: 11 },
    { id: 240, name: 'm1', typeId: 12 },
    { id: 241, name: 'singtel', typeId: 12 },
    { id: 242, name: 'starhub', typeId: 12 },
    { id: 243, name: 'chunghwa', typeId: 13 },
    { id: 244, name: 'if_taiwan_topup', typeId: 13 },
    { id: 245, name: 'ok_taiwan_topup', typeId: 13 },
    { id: 246, name: 'thailand_topup', typeId: 14 },
    { id: 247, name: 'vietnam_topup', typeId: 15 }
  ];

  for (const op of operators) {
    await prisma.iakPrabayarOperator.upsert({
      where: { id: op.id },
      update: { name: op.name, typeId: op.typeId },
      create: { id: op.id, name: op.name, typeId: op.typeId }
    });
  }

  // Reset PostgreSQL sequences to sync with manually inserted IDs
  try {
    await prisma.$executeRawUnsafe(`SELECT setval('"IakPrabayarType_id_seq"', COALESCE((SELECT MAX(id) FROM "IakPrabayarType"), 1))`);
    await prisma.$executeRawUnsafe(`SELECT setval('"IakPrabayarOperator_id_seq"', COALESCE((SELECT MAX(id) FROM "IakPrabayarOperator"), 1))`);
  } catch (e) {
    // Abaikan jika bukan PostgreSQL
  }
}
