import { PrismaClient } from '@prisma/client';

export default async function tabSeed(prisma: PrismaClient) {
  await prisma.tabMenu.createMany({
    data: [
      {
        name: 'Ringkasan', 
        icon: 'chart-pie', 
        path: 'ringkasan', 
        desc: 'Ringkasan keseluruhan',
        created_at: new Date(),
        updated_at: new Date(),
      },
      { 
        name: 'Transaksi Pulsa', 
        icon: 'history', 
        path: 'transaksi_pulsa', 
        desc: 'Transaksi Pulsa member',  
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Daftar Member', 
        icon: 'user', 
        path: 'daftar_member', 
        desc: 'Daftar membership aplikasi', 
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Produk Prabayar', 
        icon: 'list-check', 
        path: 'produk_prabayar', 
        desc: 'Daftar produk prabayar aplikasi ', 
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Pengaturan Umum', 
        icon: 'settings', 
        path: 'pengaturan_umum', 
        desc: 'Daftar pengaturan aplikasi',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Daftar Server', 
        icon: 'server', 
        path: 'daftar_server', 
        desc: 'Daftar server pulsa',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Daftar Agen', 
        icon: 'users', 
        path: 'daftar_agen', 
        desc: 'Daftar agen pulsa',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Kategori', 
        icon: 'category', 
        path: 'kategori', 
        desc: 'Daftar kategori',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Operator', 
        icon: 'antenna',
        path: 'operator',
        desc: 'Daftar operator',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Deposit', 
        icon: 'wallet',
        path: 'deposit',
        desc: 'Riwayat deposit member',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Log System', 
        icon: 'wallet',
        path: 'log',
        desc: 'Log System',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Daftar Grup', 
        icon: 'users',
        path: 'daftar_grup',
        desc: 'Daftar Grup',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Daftar Pengguna', 
        icon: 'user',
        path: 'daftar_pengguna',
        desc: 'Daftar Pengguna',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Daftar Produk Prabayar Tripay', 
        icon: 'list-check',
        path: 'daftar_produk_prabayar_tripay',
        desc: 'Daftar Produk Prabayar Tripay',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Operator Prabayar Tripay', 
        icon: 'list-check',
        path: 'daftar_operator_prabayar_tripay',
        desc: 'Daftar Operator Prabayar Tripay',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Kategori Prabayar Tripay', 
        icon: 'list-check',
        path: 'daftar_kategori_prabayar_tripay',
        desc: 'Daftar Kategori Prabayar Tripay',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Daftar Produk Prabayar IAK', 
        icon: 'user',
        path: 'daftar_produk_prabayar_iak',
        desc: 'Daftar Produk Prabayar IAK',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Daftar Operator IAK', 
        icon: 'list-check',
        path: 'daftar_operator_iak',
        desc: 'Daftar Operator IAK',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Daftar Type IAK', 
        icon: 'list-check',
        path: 'daftar_type_iak',
        desc: 'Daftar Type IAK',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Produk Pascabayar', 
        icon: 'list-check', 
        path: 'produk_pascabayar', 
        desc: 'Daftar produk pascabayar aplikasi ', 
        created_at: new Date(),
        updated_at: new Date(), 
      },
       { 
        name: 'Daftar Produk Pascabayar Tripay', 
        icon: 'list-check',
        path: 'daftar_produk_pascabayar_tripay',
        desc: 'Daftar Produk Pascabayar Tripay',
        created_at: new Date(),
        updated_at: new Date(), 
      },
        { 
        name: 'Daftar Produk Pascabayar IAK', 
        icon: 'list-check',
        path: 'daftar_produk_pascabayar_iak',
        desc: 'Daftar Produk Pascabayar IAK',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Kategori Pascabayar Tripay', 
        icon: 'list-check',
        path: 'daftar_kategori_pascabayar_tripay',
        desc: 'Daftar Kategori Pascabayar Tripay',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Operator Pascabayar Tripay', 
        icon: 'list-check',
        path: 'daftar_operator_pascabayar_tripay',
        desc: 'Daftar Operator Pascabayar Tripay',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Daftar Produk Digiflazz', 
        icon: 'list-check',
        path: 'daftar_produk_digiflazz',
        desc: 'Daftar Produk Digiflazz',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Daftar Produk Seller Digiflazz', 
        icon: 'list-check',
        path: 'daftar_produk_seller_digiflazz',
        desc: 'Daftar Produk Seller Digiflazz',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Daftar Seller Digiflazz', 
        icon: 'users',
        path: 'daftar_seller_digiflazz',
        desc: 'Daftar Seller Digiflazz',
        created_at: new Date(),
        updated_at: new Date(), 
      },
    ],
    skipDuplicates: true,
  });
}
