import { PrismaClient } from '@prisma/client';

export default async function tabSeed(prisma: PrismaClient) {
  await prisma.tabMenu.createMany({
    data: [
      {
        name: 'Ringkasan', 
        icon: 'IconChartPie', 
        path: 'ringkasan', 
        desc: 'Ringkasan keseluruhan',
        created_at: new Date(),
        updated_at: new Date(),
      },
      { 
        name: 'Transaksi Pulsa', 
        icon: 'IconHistory', 
        path: 'transaksi_pulsa', 
        desc: 'Transaksi Pulsa member',  
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Daftar Member', 
        icon: 'IconUser', 
        path: 'daftar_member', 
        desc: 'Daftar membership aplikasi', 
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Produk Prabayar', 
        icon: 'IconListCheck', 
        path: 'produk_prabayar', 
        desc: 'Daftar produk prabayar aplikasi ', 
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Pengaturan Umum', 
        icon: 'IconSettings', 
        path: 'pengaturan_umum', 
        desc: 'Daftar pengaturan aplikasi',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Daftar Server', 
        icon: 'IconServer', 
        path: 'daftar_server', 
        desc: 'Daftar server pulsa',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Daftar Agen', 
        icon: 'IconUsers', 
        path: 'daftar_agen', 
        desc: 'Daftar agen pulsa',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Kategori', 
        icon: 'IconCategory', 
        path: 'kategori', 
        desc: 'Daftar kategori',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Operator', 
        icon: 'IconAntenna',
        path: 'operator',
        desc: 'Daftar operator',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Deposit', 
        icon: 'IconWallet',
        path: 'deposit',
        desc: 'Riwayat deposit member',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Log System', 
        icon: 'IconWallet',
        path: 'log',
        desc: 'Log System',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Daftar Grup', 
        icon: 'IconUsers',
        path: 'daftar_grup',
        desc: 'Daftar Grup',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Daftar Pengguna', 
        icon: 'IconUser',
        path: 'daftar_pengguna',
        desc: 'Daftar Pengguna',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Daftar Produk Prabayar Tripay', 
        icon: 'IconListCheck',
        path: 'daftar_produk_prabayar_tripay',
        desc: 'Daftar Produk Prabayar Tripay',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Operator Prabayar Tripay', 
        icon: 'IconListCheck',
        path: 'daftar_operator_prabayar_tripay',
        desc: 'Daftar Operator Prabayar Tripay',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Kategori Prabayar Tripay', 
        icon: 'IconListCheck',
        path: 'daftar_kategori_prabayar_tripay',
        desc: 'Daftar Kategori Prabayar Tripay',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Daftar Produk Prabayar IAK', 
        icon: 'IconUser',
        path: 'daftar_produk_prabayar_iak',
        desc: 'Daftar Produk Prabayar IAK',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Daftar Operator IAK', 
        icon: 'IconListCheck',
        path: 'daftar_operator_iak',
        desc: 'Daftar Operator IAK',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Daftar Type IAK', 
        icon: 'IconListCheck',
        path: 'daftar_type_iak',
        desc: 'Daftar Type IAK',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Produk Pascabayar', 
        icon: 'IconListCheck', 
        path: 'produk_pascabayar', 
        desc: 'Daftar produk pascabayar aplikasi ', 
        created_at: new Date(),
        updated_at: new Date(), 
      },
       { 
        name: 'Daftar Produk Pascabayar Tripay', 
        icon: 'IconListCheck',
        path: 'daftar_produk_pascabayar_tripay',
        desc: 'Daftar Produk Pascabayar Tripay',
        created_at: new Date(),
        updated_at: new Date(), 
      },
        { 
        name: 'Daftar Produk Pascabayar IAK', 
        icon: 'IconListCheck',
        path: 'daftar_produk_pascabayar_iak',
        desc: 'Daftar Produk Pascabayar IAK',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Kategori Pascabayar Tripay', 
        icon: 'IconListCheck',
        path: 'daftar_kategori_pascabayar_tripay',
        desc: 'Daftar Kategori Pascabayar Tripay',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Operator Pascabayar Tripay', 
        icon: 'IconListCheck',
        path: 'daftar_operator_pascabayar_tripay',
        desc: 'Daftar Operator Pascabayar Tripay',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Daftar Produk Digiflazz', 
        icon: 'IconListCheck',
        path: 'daftar_produk_digiflazz',
        desc: 'Daftar Produk Digiflazz',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Daftar Produk Seller Digiflazz', 
        icon: 'IconListCheck',
        path: 'daftar_produk_seller_digiflazz',
        desc: 'Daftar Produk Seller Digiflazz',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Daftar Seller Digiflazz', 
        icon: 'IconUsers',
        path: 'daftar_seller_digiflazz',
        desc: 'Daftar Seller Digiflazz',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      { 
        name: 'Riwayat Transfer Saldo', 
        icon: 'IconUsers',
        path: 'riwayat_transfer_saldo',
        desc: 'Riwayat Transfer Saldo',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      {
        name: 'Laba Diambil',
        icon: 'IconWallet',
        path: 'laba_diambil',
        desc: 'Data Laba Diambil',
        created_at: new Date(),
        updated_at: new Date(), 
      },
      {
        name: 'Daftar Device',
        icon: 'IconDeviceMobile',
        path: 'daftar_device',
        desc: 'Daftar Device',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Pengumuman',
        icon: 'IconNotifications',
        path: 'pengumuman',
        desc: 'Pengumuman',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Laporan Umum',
        icon: 'IconChartPie',
        path: 'laporan_umum',
        desc: 'Laporan Umum',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Laporan Pendaftaran',
        icon: 'IconUsers',
        path: 'laporan_pendaftaran',
        desc: 'Laporan Pendaftaran',
        created_at: new Date(),
        updated_at: new Date(),
      },
    ],
    skipDuplicates: true,
  });
}
