name: CI/CD Deploy Outlet Pulsa

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "./Backend/package-lock.json"

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}

      - name: Build and push Docker image backend
        run: |
          docker build \
            --build-arg DATABASE_URL="postgresql://user:pass@localhost:5432/outletpulsa_db" \
            -t muammar88/outletpulsa-backend:1.0.0 ./Backend

          docker push muammar88/outletpulsa-backend:1.0.0

      # - name: Build and push Docker image frontend
      #   run: |
      #     docker build \
      #       --build-arg VITE_API_URL=${{ secrets.VITE_API_URL }} \
      #       -t muammar88/outletpulsa-frontend:1.0.0 ./Frontend

      #     docker push muammar88/outletpulsa-frontend:1.0.0

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.IP_SERVER_MACHINE_2 }}
          username: ${{ secrets.SSH_USER_SERVER_MACHINE_2 }}
          key: ${{ secrets.SSH_PRIVATE_KEY_SERVER_MACHINE_2 }}
          script: |
            set -e # Menghentikan script jika ada perintah penting yang gagal

            echo "📁 Pindah ke direktori project..."
            cd /home/outletpulsa/outletpulsa

            echo "🛑 1. Menghentikan seluruh container..."
            docker compose down

            # echo "🗑️ 2. Menghapus image outletpulsa-frontend..."
            # docker rmi muammar88/outletpulsa-frontend:1.0.0 || true

            echo "🗑️ 3. Menghapus image outletpulsa-backend..."
            docker rmi muammar88/outletpulsa-backend:1.0.0 || true

            # echo "📥 Pull latest image"
            # docker pull muammar88/outletpulsa-frontend:1.0.0
            docker pull muammar88/outletpulsa-backend:1.0.0

            echo "🚀 6. Menjalankan seluruh service..."
            docker compose up -d

            # echo "✅ Deployment selesai dengan sukses!"

            # echo "🔧 Mengatasi failed migration sebelumnya..."
            # docker exec -i outletpulsa_backend npx prisma migrate resolve --applied 20260622152905_add_bullmq_schedules || true

            # echo "🔧 Resolve failed migration (jika ada)..."
            # docker exec -i outletpulsa_backend npx prisma migrate resolve --rolled-back "20260625092400_add_device_code_to_otp_register" || true

            echo "📜 Run migration"
            docker exec -i outletpulsa_backend npx prisma migrate deploy

            echo "🌱 Generate Prisma Client"
            docker exec -i outletpulsa_backend npx prisma generate

            # echo "🗑️ Menghapus data tabel ProdukPascabayar di database production..."
            # echo 'DELETE FROM "ProdukPascabayar";' | docker exec -i outletpulsa_backend npx prisma db execute --stdin

            # echo "🌱 Menjalankan seed khusus produk_pascabayar..."
            # docker exec -i outletpulsa_backend npx ts-node prisma/execution/run_produk_pascabayar_seed.ts

            # echo "🎯 Run Status Laba Seeder (Transaction)"
            # docker exec -i outletpulsa_backend npx ts-node prisma/seeds/20260623-add-status-laba-transaction.seed.ts

            # echo "🔄 Run Sync Menu Seed (Menyinkronkan Menu, SubMenu, dan Tab)"
            # docker exec -i outletpulsa_backend npx ts-node prisma/seeds/sync_menu.seed.ts

            # echo "🔍 Checking Database Schema vs Prisma Schema..."
            # docker exec -i outletpulsa_backend npx ts-node prisma/execution/check_schema_diff.ts

            # echo "🏦 Run Bank Seed (Aman untuk data yang sudah ada)"
            # docker exec -i outletpulsa_backend npx ts-node prisma/seeds/bank_menu.seed.ts
