name: CI/CD Deploy Outlet Pulsa

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "./Backend/package-lock.json"

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}

      - name: Build and push Docker image backend
        run: |
          docker build \
            --build-arg DATABASE_URL="postgresql://user:pass@localhost:5432/outletpulsa_db" \
            -t muammar88/outletpulsa-backend:1.0.0 ./Backend

          docker push muammar88/outletpulsa-backend:1.0.0

      - name: Build and push Docker image frontend
        run: |
          docker build \
            --build-arg VITE_API_URL=${{ secrets.VITE_API_URL }} \
            -t muammar88/outletpulsa-frontend:1.0.0 ./Frontend

          docker push muammar88/outletpulsa-frontend:1.0.0

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.IP_SERVER_MACHINE_2 }}
          username: ${{ secrets.SSH_USER_SERVER_MACHINE_2 }}
          key: ${{ secrets.SSH_PRIVATE_KEY_SERVER_MACHINE_2 }}
          script: |
            set -e # Menghentikan script jika ada perintah penting yang gagal

            echo "📁 Pindah ke direktori project..."
            cd /home/outletpulsa/outletpulsa

            echo "🛑 1. Menghentikan seluruh container..."
            docker compose down

            echo "🗑️ 2. Menghapus image outletpulsa-frontend..."
            docker rmi muammar88/outletpulsa-frontend:1.0.0 || true

            echo "🗑️ 3. Menghapus image outletpulsa-backend..."
            docker rmi muammar88/outletpulsa-backend:1.0.0 || true

            echo "📥 Pull latest image"
            docker pull muammar88/outletpulsa-frontend:1.0.0
            docker pull muammar88/outletpulsa-backend:1.0.0



            echo "🚀 6. Menjalankan seluruh service..."
            docker compose up -d

            echo "✅ Deployment selesai dengan sukses!"

            # echo "📜 Run migration"
            docker exec -i outletpulsa_backend npx prisma migrate deploy

            # echo "🌱 Generate Prisma Client"
            docker exec -i outletpulsa_backend npx prisma generate
